#!/bin/bash
cd buildcuda
cmake .. -DIMRESH_DEBUG=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9 -DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DBUILD_DOC=OFF -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DUSE_PNG=ON -DRUN_TESTS=ON -DBUILD_EXAMPLES=ON
make -j
